
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgvyriqvlmrmdjocwirj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtndnlyaXF2bG1ybWRqb2N3aXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjI4MzcsImV4cCI6MjA1NzkzODgzN30.ulRBJaBCmPw4v_o949LyVakg6sYmwtQgaWJDCDmYX7o";

// Get the current site URL dynamically
const getSiteUrl = () => {
  let url;
  
  // Check if we're in a browser environment
  if (typeof window !== 'undefined') {
    url = window.location.origin;
    
    // For production deployments, use the origin as is
    if (!url.includes('localhost')) {
      return url;
    }
    
    // For development, localhost points to the Supabase project URL since the callback
    // can't go to localhost directly (causing the error)
    return 'https://lovable.dev';
  }
  
  // If running in a non-browser environment, provide a fallback
  return 'https://lovable.dev';
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage,
    flowType: 'pkce',
    detectSessionInUrl: true,
    debug: false
  }
});

// Helper function to set the auth redirect URL
export const configureAuthRedirect = () => {
  const redirectUrl = `${getSiteUrl()}/journal`;
  return supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo: redirectUrl
    }
  });
};
